---

- name: test variables...
  hosts: all
  vars:
    - some_junk: "1"
#  gather_facts: no # foo and bar are unavailable whether I gather facts or not.
  tasks:
    - debug: msg="Host msg={{itemlist}}"
    - debug: msg="Group msg={{grpmsg}}"
    - name: install common packages for all servers
      apt:
       name={{item}}
      with_items: "{{ itemlist }}"
      sudo: yes
